"""Add source_id to Asset model

Revision ID: 098cfb467e49
Revises: a52f5abf3e5d
Create Date: 2025-11-04 02:34:50.420090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app_core

# revision identifiers, used by Alembic.
revision = '098cfb467e49'
down_revision = 'a52f5abf3e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', app_core.db_types.GUID(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_assets_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_assets_source_id_dataset_sources",
            "dataset_sources",
            ["source_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table('coverage_jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('outputs_asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=True)

    with op.batch_alter_table('dataset_sources', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('locator',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('time_range',
               existing_type=postgresql.DATERANGE(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('user_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('aoi_geojson',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.alter_column('json_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('pdf_asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=app_core.db_types.GUID(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_uuid'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('pdf_asset_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('json_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('aoi_geojson',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('user_uuid',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('dataset_sources', schema=None) as batch_op:
        batch_op.alter_column('time_range',
               existing_type=sa.String(length=64),
               type_=postgresql.DATERANGE(),
               existing_nullable=True)
        batch_op.alter_column('locator',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('coverage_jobs', schema=None) as batch_op:
        batch_op.alter_column('outputs_asset_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('inputs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_assets_source_id_dataset_sources",
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f('ix_assets_source_id'))
        batch_op.alter_column('meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=app_core.db_types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
